[model]
# A! `vocab` should be roughly the same as the tokenizer used by trainer.py, if you are unsure about it, please leave it `0` and the trainer.py will use the same from tokenizer. Yay! focus on configuring the tokenizer instead.
vocab = 0
layer = 8
chan = 512
q_head = 8
kv_head = 4
mlp_mul = 4
bias = false # Hmm~ not recommended unless you want to load a compatible model.
drop = 0.0 # float. for pretraining 0 is good, for finetuning try 0.1+
eps = 1e-5

[train]
init_from = "scratch"
tokenizer_path = "/home/menv/src/trained_llm/SmolLM2-360M"
working_directory = "./model/mtiny_model" # The path directly stores the current model, be aware!

max_steps = 2000
log_interval = 1
save_interval = 20

dataset_train = "corpus/cus0/train.bin"
dataset_validation = "corpus/cus0/val.bin"
corpus_block_size = 64
corpus_batch_size = 4

optimizer_learning_rate = 6e-4

adamw_weight_decay = 1e-1
adamw_beta1 = 0.9
adamw_beta2 = 0.95

[system]
device = "cpu"
dtype = "bfloat16"
