[character]
name = ""
peer = ""
card = """
"""

[datasets.dialogue]
description = ''
scenarios = [
]

min_turns = 3
max_turns = 7

examples = """
"""
inject_prompts = """
"""

template = """
# Character
{character_card}

{inject_prompts}

# Scenario
{scenario}

# Requirements
- 3-7 dialogue turns.
- Stay focused on the scenario.
- Write only dialogue.
- Do not write narration or internal thoughts.

# Examples
{examples}

# Goal
Imitate the format of examples.
Generate one natural conversation.
"""
censored_terms = ["language model", "training data", "assistant", "user", ":", "mommy", "mother", "father", "dad", "brother", "sister", "uncle", "aunt", "my dog", "pet dog", "pet cat", "question continues", "this question continues", "the response maintains", "conversation flow", "parent", "you are sensei", "generate only","anonymous", "'s next reply", "choose one letter", "dialogue options", "story scenario", "additional information", "what does sensei want to see next", "prompt", "hidden prompt", "hidden instruction", "hidden instrtuctions", "policy", "policies", "training", "dataset"]
