Import("hip_env")

hip_env.Append(
	CXXFLAGS=[
		"-std=c++20",
		"-O2",
	],
)

hip_env.Program(
	target="hip-test",
	source=[
		"main.cpp",
	],
	LIBS=[
		"shark",
		"boost_json",
	],
	LIBPATH=[
		"#build/shark",
	],
)
