import os

# print("PATH =", os.environ["PATH"])

cpp_env = Environment(
	ENV=os.environ,
	CXX="clang++",
	CXXFLAGS=[
		"-std=c++20",
		"-O2",
	],
)

hip_env = Environment(
	ENV=os.environ,
	CXX="hipcc",
	CC="hipcc",
	CXXFLAGS=[
		"-std=c++20",
		"-O2",
	],
)
# print("scons ENV PATH:", hip_env["ENV"].get("PATH"))
# print("scons hipcc:", hip_env.WhereIs("hipcc"))
# exit()

cpp_env.Tool("compilation_db")
hip_env.Tool("compilation_db")


Export("cpp_env", "hip_env")


shark = SConscript(
	"shark/SConscript",
	variant_dir="build/shark",
	duplicate=False,
)

# tell clangd infer HIP mode from hipcc
hip_env.Append(
    CXXFLAGS=[
        "-x",
        "hip",
    ],
	CPPPATH=[
		"#shark/include",
	],
)


SConscript(
	"hip-test/SConscript",
	variant_dir="build/hip-test",
	duplicate=False,
)


cpp_env.CompilationDatabase(
	"compile_commands.json"
)
